"""
Renders a self-contained HTML report from score_tier() results across all
three difficulty tiers -- the artifact you'd show in a demo/pitch video.

Usage:
    python3 -m scorer.report --datasets-dir datasets --out report.html
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from scorer.score import score_tier

TIERS = ["easy", "medium", "hard"]

PALETTE = {
    "bg": "#0b0f14", "panel": "#131a22", "border": "#22303c",
    "text": "#e6edf3", "muted": "#8b98a5",
    "accent": "#22c55e", "warn": "#f59e0b", "bad": "#ef4444",
    "bar": "#3b82f6",
}


def _pct(x):
    return "n/a" if x is None else f"{x*100:.1f}%"


def _bar(label, value, color):
    v = 0 if value is None else value
    width = max(0, min(100, v * 100))
    return f"""
    <div class="bar-row">
      <div class="bar-label">{label}</div>
      <div class="bar-track"><div class="bar-fill" style="width:{width:.1f}%;background:{color}"></div></div>
      <div class="bar-value">{_pct(value)}</div>
    </div>"""


def render_html(results: dict) -> str:
    tier_sections = []
    for tier in TIERS:
        r = results[tier]
        m, i = r["matching"], r["issue_detection"]
        tier_sections.append(f"""
    <section class="tier-card">
      <h2>{tier.upper()} <span class="n">({r['n_records']} records, {i['n_real_issues']} with injected issues)</span></h2>
      <div class="cols">
        <div class="col">
          <h3>Matching (linked vs unmatched)</h3>
          {_bar("Precision", m['precision'], PALETTE['bar'])}
          {_bar("Recall", m['recall'], PALETTE['bar'])}
          {_bar("F1", m['f1'], PALETTE['accent'])}
        </div>
        <div class="col">
          <h3>Issue detection</h3>
          {_bar("Precision", i['precision'], PALETTE['bar'])}
          {_bar("Recall", i['recall'], PALETTE['bar'])}
          {_bar("Attribution accuracy", i['attribution_accuracy'], PALETTE['accent'])}
          {_bar("False positive rate", i['false_positive_rate'], PALETTE['bad'])}
        </div>
      </div>
    </section>""")

    overall_recall = [results[t]["issue_detection"]["recall"] for t in TIERS
                       if results[t]["issue_detection"]["recall"] is not None]
    degrade_note = ""
    if len(overall_recall) == 3 and overall_recall[0] >= overall_recall[-1]:
        degrade_note = ("<p class='note'>Signal check: issue-detection recall degrades from "
                         f"easy ({_pct(overall_recall[0])}) to hard ({_pct(overall_recall[-1])}) "
                         "as expected — the difficulty tiers are doing their job.</p>")

    return f"""<title>ReconArena Report</title>
<style>
  :root {{ color-scheme: dark; }}
  body {{ background:{PALETTE['bg']}; color:{PALETTE['text']}; font-family: -apple-system, Segoe UI, sans-serif; margin:0; padding:32px 24px 64px; }}
  .wrap {{ max-width: 860px; margin: 0 auto; }}
  h1 {{ font-size: 1.6rem; margin-bottom: 4px; }}
  .subtitle {{ color:{PALETTE['muted']}; margin-top:0; margin-bottom: 28px; font-size:0.95rem; }}
  .tier-card {{ background:{PALETTE['panel']}; border:1px solid {PALETTE['border']}; border-radius:12px; padding:20px 22px; margin-bottom:18px; }}
  .tier-card h2 {{ margin:0 0 14px; font-size:1.1rem; text-transform:capitalize; }}
  .tier-card h2 .n {{ color:{PALETTE['muted']}; font-weight:400; font-size:0.85rem; text-transform:none; }}
  .cols {{ display:flex; gap:28px; flex-wrap:wrap; }}
  .col {{ flex:1; min-width:260px; }}
  .col h3 {{ font-size:0.8rem; text-transform:uppercase; letter-spacing:0.04em; color:{PALETTE['muted']}; margin:0 0 10px; }}
  .bar-row {{ display:flex; align-items:center; gap:10px; margin-bottom:8px; font-size:0.85rem; }}
  .bar-label {{ width:150px; flex-shrink:0; color:{PALETTE['muted']}; }}
  .bar-track {{ flex:1; height:8px; background:#1c2530; border-radius:4px; overflow:hidden; }}
  .bar-fill {{ height:100%; border-radius:4px; }}
  .bar-value {{ width:50px; text-align:right; flex-shrink:0; font-variant-numeric:tabular-nums; }}
  .note {{ color:{PALETTE['muted']}; font-size:0.85rem; }}
  footer {{ color:{PALETTE['muted']}; font-size:0.75rem; margin-top:32px; }}
</style>
<div class="wrap">
  <h1>ReconArena &mdash; Baseline Agent Report</h1>
  <p class="subtitle">Rule-based reference agent scored against ground truth across difficulty tiers.</p>
  {''.join(tier_sections)}
  {degrade_note}
  <footer>Generated by scorer/report.py &middot; Razorpay AI Buildathon &middot; ReconArena (Open Track)</footer>
</div>
"""


def main():
    parser = argparse.ArgumentParser(description="Render ReconArena HTML report")
    parser.add_argument("--datasets-dir", type=str, default="datasets")
    parser.add_argument("--out", type=str, default="report.html")
    args = parser.parse_args()

    datasets_dir = Path(args.datasets_dir)
    results = {tier: score_tier(datasets_dir / tier) for tier in TIERS}
    html = render_html(results)
    Path(args.out).write_text(html)
    print(f"wrote report -> {args.out}")
    print(json.dumps({t: results[t]["issue_detection"] for t in TIERS}, indent=2))


if __name__ == "__main__":
    main()
